#!/usr/bin/env bash
set -euo pipefail

#############################################
# install.sh — first-time Docker install of assets.i-portal.me
#
#   sudo ./scripts/install.sh
#
# Asks a few questions, writes .env, runs the preflight (APP_KEY, free port),
# builds the image and starts the stack. Re-running is safe: it refuses to
# overwrite an existing .env unless you say so.
#############################################

log()  { echo -e "\n\033[1;32m[INFO]\033[0m $*"; }
warn() { echo -e "\n\033[1;33m[WARN]\033[0m $*"; }
err()  { echo -e "\n\033[1;31m[ERR ]\033[0m $*" >&2; }
die()  { err "$*"; exit 1; }

prompt() { # var, msg, default(optional)
  local var="$1" msg="$2" def="${3:-}" val=""
  if [[ -n "$def" ]]; then read -r -p "$msg [$def]: " val; val="${val:-$def}"; else read -r -p "$msg: " val; fi
  printf -v "$var" "%s" "$val"
}
prompt_secret() { local var="$1" msg="$2" val=""; read -r -s -p "$msg: " val; echo; printf -v "$var" "%s" "$val"; }
yesno() { local ans=""; read -r -p "$1 [${2:-y}]: " ans; ans="${ans:-${2:-y}}"; [[ "$ans" =~ ^[Yy]$ ]]; }
ensure_min_len() { [[ "${#1}" -ge "$2" ]] || die "$3"; }
to_safe_token() { local s; s="$(echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_]+/_/g; s/^_+//; s/_+$//; s/__+/_/g')"; echo "${s:-app}"; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVFILE="${REPO_ROOT}/.env"

log "=== assets.i-portal.me — Docker install ==="
command -v docker >/dev/null 2>&1 || die "Docker is not installed. See https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 plugin not found. See https://docs.docker.com/compose/install/"
[[ -f "${REPO_ROOT}/docker-compose.yml" ]] || die "docker-compose.yml not found at ${REPO_ROOT}"

prompt APP_NAME "App name" "assets.i-portal.me"
prompt WEB_PORT "Host port to publish the app on" "8080"
APP_URL="http://localhost:${WEB_PORT}"
if yesno "Serve on a custom domain/URL (behind a reverse proxy)?" "n"; then
  prompt APP_URL "Public application URL (e.g. https://assets.example.com)" "$APP_URL"
fi
prompt APP_TIMEZONE "Timezone" "Europe/Athens"

prompt DB_NAME_RAW "Database name" "assets"; DB_NAME="$(to_safe_token "$DB_NAME_RAW")"
prompt DB_USER_RAW "Database user" "assets"; DB_USER="$(to_safe_token "$DB_USER_RAW")"
prompt_secret DB_PASS "Database password (min 8 chars)"; ensure_min_len "$DB_PASS" 8 "Database password must be at least 8 characters."
prompt_secret DB_ROOT_PASS "MySQL root password (min 8 chars)"; ensure_min_len "$DB_ROOT_PASS" 8 "Root password must be at least 8 characters."

ADMIN_NAME="Admin"; ADMIN_USERNAME="admin"; ADMIN_EMAIL=""; ADMIN_PASS=""
if yesno "Create the first admin user on first boot?" "y"; then
  prompt ADMIN_NAME "Admin full name" "Admin"
  prompt ADMIN_USERNAME "Admin username (you log in with this)" "admin"
  prompt ADMIN_EMAIL "Admin email"
  prompt_secret ADMIN_PASS "Admin password (min 10 chars)"; ensure_min_len "$ADMIN_PASS" 10 "Admin password must be at least 10 characters."
fi

if [[ -f "$ENVFILE" ]]; then
  warn "An .env already exists at ${ENVFILE}"
  yesno "Back it up to .env.bak and overwrite?" "n" || die "Aborted. Remove or rename the existing .env first."
  cp -f "$ENVFILE" "${ENVFILE}.bak"
fi

log "Writing ${ENVFILE}"
cat > "$ENVFILE" <<ENV
# Generated by scripts/install.sh — consumed by docker-compose.yml
APP_NAME=${APP_NAME}
APP_ENV=production
APP_DEBUG=false
APP_URL=${APP_URL}
APP_TIMEZONE=${APP_TIMEZONE}
APP_KEY=

WEB_PORT=${WEB_PORT}

DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASS}
DB_ROOT_PASSWORD=${DB_ROOT_PASS}

CACHE_STORE=database
SESSION_DRIVER=database
QUEUE_CONNECTION=database

ADMIN_NAME=${ADMIN_NAME}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASS}

# Title deed import (optional — can also be pasted in Settings → Portal)
ANTHROPIC_API_KEY=
ANTHROPIC_MODEL=claude-opus-5
ENV
chmod 600 "$ENVFILE"

# APP_KEY + free port
# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/docker-preflight.sh"
docker_preflight

log "Building the image and starting the stack (first build takes a few minutes)..."
( cd "$REPO_ROOT" && docker compose up -d --build )

log "DONE."
echo "-------------------------------------------"
echo "URL:        $(env_get APP_URL)   (host port $(env_get WEB_PORT))"
echo "Login:      ${ADMIN_USERNAME:-admin}  (username, not email)"
echo "Env file:   ${ENVFILE}"
echo "-------------------------------------------"
echo "  docker compose logs -f app          # watch first boot (migrations, admin)"
echo "  ./scripts/new_deploy.sh             # update after git pull"
echo "  sudo ./scripts/backup.sh --install-cron 02:30"
echo "-------------------------------------------"
